#############################################################################
# Makefile for building: bin/tarot
# Generated by qmake (2.01a) (Qt 4.8.7) on: mer. nov. 2 14:59:42 2016
# Project:  tarot.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile tarot.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++14 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/Joueur.cpp \
		src/Humain.cpp \
		src/ACarte.cpp \
		src/AForme.cpp \
		src/Pique.cpp \
		src/Coeur.cpp \
		src/Carreau.cpp \
		src/Trefle.cpp \
		src/Paquet.cpp \
		src/Atout.cpp \
		src/LePetit.cpp \
		src/Le21.cpp \
		src/Excuse.cpp \
		src/Equipe.cpp \
		src/Chien.cpp \
		src/Etat.cpp \
		src/Partie.cpp \
		src/Distribuer.cpp \
		src/Enchere.cpp \
		src/Niveau.cpp \
		src/Garde.cpp \
		src/IA.cpp \
		src/Constantes.cpp \
		src/Prise.cpp \
		src/Passer.cpp \
		src/AppelRoi.cpp \
		src/CreationChien.cpp \
		src/JouerLeJeux.cpp \
		src/Cavalier.cpp \
		src/Dame.cpp \
		src/Roi.cpp \
		src/Simple.cpp \
		src/Valet.cpp \
		src/Tete.cpp \
		src/Filtre.cpp \
		src/Pli.cpp \
		src/Classement.cpp 
OBJECTS       = main.o \
		Joueur.o \
		Humain.o \
		ACarte.o \
		AForme.o \
		Pique.o \
		Coeur.o \
		Carreau.o \
		Trefle.o \
		Paquet.o \
		Atout.o \
		LePetit.o \
		Le21.o \
		Excuse.o \
		Equipe.o \
		Chien.o \
		Etat.o \
		Partie.o \
		Distribuer.o \
		Enchere.o \
		Niveau.o \
		Garde.o \
		IA.o \
		Constantes.o \
		Prise.o \
		Passer.o \
		AppelRoi.o \
		CreationChien.o \
		JouerLeJeux.o \
		Cavalier.o \
		Dame.o \
		Roi.o \
		Simple.o \
		Valet.o \
		Tete.o \
		Filtre.o \
		Pli.o \
		Classement.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		tarot.pro
QMAKE_TARGET  = tarot
DESTDIR       = bin/
TARGET        = bin/tarot

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)


Makefile: tarot.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile tarot.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile tarot.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/tarot1.0.0 || $(MKDIR) .tmp/tarot1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/tarot1.0.0/ && $(COPY_FILE) --parents src/Joueur.h src/Humain.h src/ACarte.h src/AForme.h src/Pique.h src/Coeur.h src/Carreau.h src/Trefle.h src/Paquet.h src/Atout.h src/LePetit.h src/Le21.h src/Excuse.h src/Equipe.h src/Chien.h src/Etat.h src/Partie.h src/Distribuer.h src/Enchere.h src/Niveau.h src/Garde.h src/IA.h src/Constantes.h src/Prise.h src/Passer.h src/AppelRoi.h src/CreationChien.h src/JouerLeJeux.h src/Valet.h src/Tete.h src/Cavalier.h src/Simple.h src/Dame.h src/Roi.h src/Filtre.h src/Pli.h src/Classement.h .tmp/tarot1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/Joueur.cpp src/Humain.cpp src/ACarte.cpp src/AForme.cpp src/Pique.cpp src/Coeur.cpp src/Carreau.cpp src/Trefle.cpp src/Paquet.cpp src/Atout.cpp src/LePetit.cpp src/Le21.cpp src/Excuse.cpp src/Equipe.cpp src/Chien.cpp src/Etat.cpp src/Partie.cpp src/Distribuer.cpp src/Enchere.cpp src/Niveau.cpp src/Garde.cpp src/IA.cpp src/Constantes.cpp src/Prise.cpp src/Passer.cpp src/AppelRoi.cpp src/CreationChien.cpp src/JouerLeJeux.cpp src/Cavalier.cpp src/Dame.cpp src/Roi.cpp src/Simple.cpp src/Valet.cpp src/Tete.cpp src/Filtre.cpp src/Pli.cpp src/Classement.cpp .tmp/tarot1.0.0/ && (cd `dirname .tmp/tarot1.0.0` && $(TAR) tarot1.0.0.tar tarot1.0.0 && $(COMPRESS) tarot1.0.0.tar) && $(MOVE) `dirname .tmp/tarot1.0.0`/tarot1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/tarot1.0.0

run: $(./bin/tarot)

clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core



####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: src/main.cpp src/Joueur.h \
		src/ACarte.h \
		src/Niveau.h \
		src/Pli.h \
		src/Humain.h \
		src/Paquet.h \
		src/Partie.h \
		src/Chien.h \
		src/Equipe.h \
		src/Classement.h \
		src/IA.h \
		src/Distribuer.h \
		src/Etat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

Joueur.o: src/Joueur.cpp src/Joueur.h \
		src/ACarte.h \
		src/Niveau.h \
		src/Pli.h \
		src/Constantes.h \
		src/Excuse.h \
		src/Equipe.h \
		src/Partie.h \
		src/Chien.h \
		src/Paquet.h \
		src/Classement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Joueur.o src/Joueur.cpp

Humain.o: src/Humain.cpp src/Humain.h \
		src/Joueur.h \
		src/ACarte.h \
		src/Niveau.h \
		src/Pli.h \
		src/Passer.h \
		src/AForme.h \
		src/Tete.h \
		src/Atout.h \
		src/Excuse.h \
		src/Coeur.h \
		src/Trefle.h \
		src/Pique.h \
		src/Carreau.h \
		src/Filtre.h \
		src/Constantes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Humain.o src/Humain.cpp

ACarte.o: src/ACarte.cpp src/ACarte.h \
		src/Coeur.h \
		src/AForme.h \
		src/Tete.h \
		src/Valet.h \
		src/Cavalier.h \
		src/Dame.h \
		src/Roi.h \
		src/Excuse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ACarte.o src/ACarte.cpp

AForme.o: src/AForme.cpp src/AForme.h \
		src/ACarte.h \
		src/Tete.h \
		src/Simple.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AForme.o src/AForme.cpp

Pique.o: src/Pique.cpp src/Pique.h \
		src/AForme.h \
		src/ACarte.h \
		src/Tete.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Pique.o src/Pique.cpp

Coeur.o: src/Coeur.cpp src/Coeur.h \
		src/AForme.h \
		src/ACarte.h \
		src/Tete.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Coeur.o src/Coeur.cpp

Carreau.o: src/Carreau.cpp src/Carreau.h \
		src/AForme.h \
		src/ACarte.h \
		src/Tete.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Carreau.o src/Carreau.cpp

Trefle.o: src/Trefle.cpp src/Trefle.h \
		src/AForme.h \
		src/ACarte.h \
		src/Tete.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Trefle.o src/Trefle.cpp

Paquet.o: src/Paquet.cpp src/Paquet.h \
		src/ACarte.h \
		src/Coeur.h \
		src/AForme.h \
		src/Tete.h \
		src/Pique.h \
		src/Carreau.h \
		src/Trefle.h \
		src/Valet.h \
		src/Simple.h \
		src/Cavalier.h \
		src/Dame.h \
		src/Roi.h \
		src/Excuse.h \
		src/Atout.h \
		src/LePetit.h \
		src/Le21.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Paquet.o src/Paquet.cpp

Atout.o: src/Atout.cpp src/Atout.h \
		src/ACarte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Atout.o src/Atout.cpp

LePetit.o: src/LePetit.cpp src/LePetit.h \
		src/Atout.h \
		src/ACarte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LePetit.o src/LePetit.cpp

Le21.o: src/Le21.cpp src/Le21.h \
		src/Atout.h \
		src/ACarte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Le21.o src/Le21.cpp

Excuse.o: src/Excuse.cpp src/Excuse.h \
		src/ACarte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Excuse.o src/Excuse.cpp

Equipe.o: src/Equipe.cpp src/Equipe.h \
		src/Joueur.h \
		src/ACarte.h \
		src/Niveau.h \
		src/Pli.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Equipe.o src/Equipe.cpp

Chien.o: src/Chien.cpp src/Chien.h \
		src/ACarte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Chien.o src/Chien.cpp

Etat.o: src/Etat.cpp src/Etat.h \
		src/Partie.h \
		src/Joueur.h \
		src/ACarte.h \
		src/Niveau.h \
		src/Pli.h \
		src/Chien.h \
		src/Paquet.h \
		src/Equipe.h \
		src/Classement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Etat.o src/Etat.cpp

Partie.o: src/Partie.cpp src/Partie.h \
		src/Joueur.h \
		src/ACarte.h \
		src/Niveau.h \
		src/Pli.h \
		src/Chien.h \
		src/Paquet.h \
		src/Equipe.h \
		src/Classement.h \
		src/Distribuer.h \
		src/Etat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Partie.o src/Partie.cpp

Distribuer.o: src/Distribuer.cpp src/Distribuer.h \
		src/Etat.h \
		src/Partie.h \
		src/Joueur.h \
		src/ACarte.h \
		src/Niveau.h \
		src/Pli.h \
		src/Chien.h \
		src/Paquet.h \
		src/Equipe.h \
		src/Classement.h \
		src/Constantes.h \
		src/Enchere.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Distribuer.o src/Distribuer.cpp

Enchere.o: src/Enchere.cpp src/Enchere.h \
		src/Etat.h \
		src/Partie.h \
		src/Joueur.h \
		src/ACarte.h \
		src/Niveau.h \
		src/Pli.h \
		src/Chien.h \
		src/Paquet.h \
		src/Equipe.h \
		src/Classement.h \
		src/Passer.h \
		src/Distribuer.h \
		src/AppelRoi.h \
		src/CreationChien.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Enchere.o src/Enchere.cpp

Niveau.o: src/Niveau.cpp src/Niveau.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Niveau.o src/Niveau.cpp

Garde.o: src/Garde.cpp src/Garde.h \
		src/Niveau.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Garde.o src/Garde.cpp

IA.o: src/IA.cpp src/IA.h \
		src/Joueur.h \
		src/ACarte.h \
		src/Niveau.h \
		src/Pli.h \
		src/Constantes.h \
		src/Filtre.h \
		src/Trefle.h \
		src/AForme.h \
		src/Tete.h \
		src/Carreau.h \
		src/Pique.h \
		src/Coeur.h \
		src/Partie.h \
		src/Chien.h \
		src/Paquet.h \
		src/Equipe.h \
		src/Classement.h \
		src/Atout.h \
		src/Excuse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IA.o src/IA.cpp

Constantes.o: src/Constantes.cpp src/Constantes.h \
		src/ACarte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Constantes.o src/Constantes.cpp

Prise.o: src/Prise.cpp src/Prise.h \
		src/Niveau.h \
		src/Garde.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Prise.o src/Prise.cpp

Passer.o: src/Passer.cpp src/Passer.h \
		src/Niveau.h \
		src/Prise.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Passer.o src/Passer.cpp

AppelRoi.o: src/AppelRoi.cpp src/AppelRoi.h \
		src/Etat.h \
		src/Partie.h \
		src/Joueur.h \
		src/ACarte.h \
		src/Niveau.h \
		src/Pli.h \
		src/Chien.h \
		src/Paquet.h \
		src/Equipe.h \
		src/Classement.h \
		src/CreationChien.h \
		src/Trefle.h \
		src/AForme.h \
		src/Tete.h \
		src/Coeur.h \
		src/Pique.h \
		src/Carreau.h \
		src/Roi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AppelRoi.o src/AppelRoi.cpp

CreationChien.o: src/CreationChien.cpp src/CreationChien.h \
		src/Etat.h \
		src/Partie.h \
		src/Joueur.h \
		src/ACarte.h \
		src/Niveau.h \
		src/Pli.h \
		src/Chien.h \
		src/Paquet.h \
		src/Equipe.h \
		src/Classement.h \
		src/JouerLeJeux.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CreationChien.o src/CreationChien.cpp

JouerLeJeux.o: src/JouerLeJeux.cpp src/JouerLeJeux.h \
		src/Etat.h \
		src/Partie.h \
		src/Joueur.h \
		src/ACarte.h \
		src/Niveau.h \
		src/Pli.h \
		src/Chien.h \
		src/Paquet.h \
		src/Equipe.h \
		src/Classement.h \
		src/Distribuer.h \
		src/Constantes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JouerLeJeux.o src/JouerLeJeux.cpp

Cavalier.o: src/Cavalier.cpp src/Cavalier.h \
		src/Tete.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cavalier.o src/Cavalier.cpp

Dame.o: src/Dame.cpp src/Dame.h \
		src/Tete.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Dame.o src/Dame.cpp

Roi.o: src/Roi.cpp src/Roi.h \
		src/Tete.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Roi.o src/Roi.cpp

Simple.o: src/Simple.cpp src/Simple.h \
		src/Tete.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Simple.o src/Simple.cpp

Valet.o: src/Valet.cpp src/Valet.h \
		src/Tete.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Valet.o src/Valet.cpp

Tete.o: src/Tete.cpp src/Tete.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tete.o src/Tete.cpp

Filtre.o: src/Filtre.cpp src/Filtre.h \
		src/ACarte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Filtre.o src/Filtre.cpp

Pli.o: src/Pli.cpp src/Pli.h \
		src/ACarte.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Pli.o src/Pli.cpp

Classement.o: src/Classement.cpp src/Classement.h \
		src/Joueur.h \
		src/ACarte.h \
		src/Niveau.h \
		src/Pli.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Classement.o src/Classement.cpp

####### Install

install:   FORCE

uninstall:   FORCE

.PHONY: run clean


FORCE:

